language: java
#language: node_js
#node_js:
#  - 12.2.0

matrix:
  include:
    - os: linux
      dist: trusty

cache:
  directories:
    - node_modules
            
services:
  - docker    

before_install:
    - export GPG_TTY=/dev/pts/4
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    - docker version
    - docker info
    - export project_version=1.0.0
    - echo $project_version


install:
    docker build -f Dockerfile -t jsoagger/jsoagger-webdev:$project_version .      
    

deploy: 
    - provider: script
      script: 
        - docker build  -f Dockerfile-prod -t jsoagger/jsoagger-web:$project_version .
      on:
        branch: master

    - provider: script
      script: 
        - docker build  -f Dockerfile-prod -t jsoagger/jsoagger-web:$project_version .
      on:
        tags: true
        all_branches: true
         
        
