language: java

# -------------  ALL BRANCHES FIRE MVN INSTALL  ------------- ------------- --------
# DEVELOP: BUILD ON COMMIT (NO DEPLOY)
# MASTER: BUILD ON COMMIT (NO DEPLOY)
# +++++++++++++  STABLE AND TAGS FIRE DEPLOY    ++++++++++++++++++++++++++++++++++++
# STABLE: BUILD ON COMMIT + DEPLOY SNAPSHOT RELEASE
# TAGS: BUILD ON COMMIT + DEPLOY SONATYPE VERSION  RELEASE
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Be aware when adding 'branch.only' they can exclude tags deployment is not fired
# -------------------------- ------------- ------------- ------------- ------------- 


matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk11
            
cache:
    directories:
    - $HOME/.m2/repository

script:
  - echo PATH = ${PATH}
  - echo $JAVA_HOME
  - java -version


before_install:
    - export GPG_TTY=/dev/pts/4
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install: 
    mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
      
      
before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')


deploy: 
# 1. Trigger a snapshot deploy when commit a stable version
    - provider: script
      script: bash .travis/snapshot.sh 
      skip_cleanup: true
      on:
        branch: stable

# 1. Trigger a version deploy when a commit on tag
    - provider: script
      script: bash .travis/release.sh 
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
 

    - provider: releases
      api_key:
          secure: b6vylD4uN84KnsNlcu8ctw2LLk4O+8sDEilDgRnnMrfo/mYrKPTVzhbZsQqLgSskF92RcZ3QL89E5+hVEV4W0+NqnKoPdUireV/7aZ1Udd86/KU7IseSXyOtVo9LAtcIofuQvfDIuK9qr3h1ba6e2c4wpMmsfTiXlDBvXCAmhGA6CM3/EArI9qTXqSBCUAA5/R7XFMyzo3HaDd2B92xC/8u1zNn0eW79T3zP+qZ0RmLnrVJcwBf6cRUvsP41uxnD9E3XDuQH5Wo28xzhMsrbvlrE9Ql0UfQgx9po9Ye9kX1WzAR3Jjl4cFX+H60y4TONxqvd6i80eHmUfa5ZzHd3fqfOLtRL2ro3hKUrVpdgnjJxHbn3blTK1gV3IDe2yIhO+zZziCMgS7eSMveCYWtOdHgrnL/cCbCOtydR3HGmNp8QM/pKIOJn6c5wbeCWC5qAEzQIMFryn3g5SWxhC++g78guiZH06f1LE2K/TyjzyZQNtctt3tq/vxPMO6/vIjp/7nbfSvYmKXkWm9ZHytjZcizXk+PE3/SF6g2cizQQKoEYr6mxNllFC3el8TCLiqw/nuLeqsrgh4q7yXPnfVSLmXCwjphKqzFBSbIotpETYOWazb2rgtQE+7sss1OK8QFDYt2JWe1i1CsLrdYcrloOwuJwRsPhXP4+W5lXakYyz1Q=
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
        
        
