# docker build -t jsoagger/jsoagger-web:latest

# base image
FROM node:12.2.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
#COPY package.json /app/package.json
RUN npm install --silent
#RUN npm install react-scripts@3.0.1 -g --silent

# Build the app
COPY . /app

RUN npm rebuild node-sass
RUN npm run build

ARG JSOAGGER_API_URL="PLEASE_SET JSOAGGER_API_URL IN YOUR ENV"
ENV JSOAGGER_API_URL="${JSOAGGER_API_URL}"

CMD [REACT_APP_BACKEND_HOST=$JSOAGGER_API_URL, "npm", "start"]